spring:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis}
    database: 0
  data:
    redis:
      repositories:
        enabled: false # disabled redis repositories
