server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8


spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./doc
  jackson:
    property-naming-strategy: SNAKE_CASE
  messages:
    basename: i18n/messages
    encoding: utf-8

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readynessstate:
      enabled: true
    livenessstate:
      enabled: true
