server:
  port: 8080

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./doc
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readynessstate:
      enabled: true
    livenessstate:
      enabled: true
