server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
  compression:
    enabled: true


spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: true
  messages:
    basename: i18n/messages
    encoding: utf-8
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./doc

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-headers: '*'
        allowed-methods: '*'
        allow-credentials: false # 设置为true时，allowed-origins不能为'*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
