server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, shutdown
  health:
    readynessstate:
      enabled: true
    livenessstate:
      enabled: true

