# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  displayName: Download gpg Secure file
  inputs:
    secureFile: '8A9A95864F12F7A70F1DC31F2233ACD21B562294.asc'
  name: privateKeyRing
- task: CmdLine@2
  inputs:
    script: 'gpg --import --batch --passphrase $(GPG-PASSPHRASE) $(privateKeyRing.secureFilePath)'
  displayName: Import gpg private key
- task: DownloadSecureFile@1
  displayName: Download settings.xml
  inputs:
    secureFile: 'settings.xml'
  name: settingsXml
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir ${HOME}/.m2
      cp "$(settingsXml.secureFilePath)" "${HOME}/.m2"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-DskipTests=true -P release'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8' # Optional. Options: default, 1.14, 1.13, 1.12, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m' # Optional
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
    