spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: ${NACOS_SERVER:http://127.0.0.1:8848}
        username: nacos
        password: nacos
      config:
        server-addr: ${NACOS_SERVER:http://127.0.0.1:8848}
        username: nacos
        password: nacos
        file-extension: yaml
