framework:
  doc:
    smart-doc:
      enabled: true
      outPath: "doc/api"
      allInOne: true
      coverOld: true
      isStrict: true
      adoc: true
      projectName: ${spring.application.name}