spring:
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: ${HOST_CONSUL:127.0.0.1}
      port: ${PORT_CONSUL:8500}
      discovery:
        enabled: true
        register: true
      config:
        format: YAML