@startuml
'https://plantuml.com/component-diagram

[framework-core]
[framework-model]

package "framework-config" {
  [framework-config-nacos]
  [framework-config-eureka]
  [framework-config-configcenter]
}

package framework-data {
  [framework-data-jpa]
  [framework-data-mybatis]
  [framework-data-redis]
}
package framework-doc {
  [framework-doc-swagger]
  [framework-doc-smart-doc]
}
[framework-global-id]
[framework-logging]
[framework-message-kafka]
[framework-message-websocket]
[framework-microservice]
[framework-schedule]
[framework-utils]
[framework-web]
[framework-cache-redis]
@enduml