spring:
  aop:
    proxy-target-class: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: ${DB_DIALECT:com.github.caijh.framework.data.dialect.mysql.CustomMySqlDialect}
