eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      enabled: true
    circuitbreaker:
      hystrix:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
  compression:
    request:
      enabled: false #是否对请求进行GZIP压缩
      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
      min-request-size: 2048 #超过该大小的请求会被压缩
    response:
      enabled: false #是否对响应进行GZIP压缩

hystrix:
  metrics:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
