spring:
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true

ribbon:
  eager-load:
    enabled: true # 开启ribbon饥饿加载

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true # feign允许开启hystrix后, 会自动把所有服务的feign接口下的方法加入到断路器监控中
  compression:
    request:
      enabled: false #是否对请求进行GZIP压缩
      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
      min-request-size: 2048 #超过该大小的请求会被压缩
    response:
      enabled: false #是否对响应进行GZIP压缩

hystrix:
  metrics:
    enabled: true
